/* Play It My Way — offline service worker (generated by docs/build-pages.js)
 *
 * Caches the SITE'S OWN FILES so the games work with no connection. It stores
 * nothing about the child: no scores, no progress, no identifiers, no
 * analytics. There is deliberately no push code here — push would require a
 * per-device subscription held by a third party, which this site does not do.
 */
const CACHE = 'pimw-e343a6e1';

const PRECACHE = [
  "/",
  "/404",
  "/apple-touch-icon.png",
  "/components.css",
  "/components.js",
  "/disclaimer",
  "/favicon.svg",
  "/fonts/fredoka-400.woff2",
  "/fonts/fredoka-600.woff2",
  "/fonts/fredoka-700.woff2",
  "/for-teachers",
  "/games/",
  "/games/2048-slider/",
  "/games/balloon-pop/",
  "/games/catch-falling-object/",
  "/games/clock-shop/",
  "/games/code-the-robot/",
  "/games/color-matcher/",
  "/games/counting-game/",
  "/games/dot-to-dot/",
  "/games/drawing-pad/",
  "/games/first-strokes/",
  "/games/geography-explorer/",
  "/games/math-puzzle/",
  "/games/memory-game/",
  "/games/minesweeper/",
  "/games/one-line-draw/",
  "/games/rock-paper-scissors/",
  "/games/science-trivia/",
  "/games/sentence-builder/",
  "/games/silly-story-builder/",
  "/games/sort-it-out/",
  "/games/sound-it-out/",
  "/games/sudoku/",
  "/games/tic-tac-toe/",
  "/games/trace-letters/",
  "/games/trace-name/",
  "/games/trace-shapes/",
  "/games/whack-a-mole/",
  "/games/word-guess/",
  "/games/word-scramble/",
  "/icons/icon-192.png",
  "/icons/icon-512.png",
  "/icons/icon-maskable-512.png",
  "/privacy-policy",
  "/styles.css",
  "/tokens.css"
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE)
      // individually, so one bad URL cannot fail the whole install
      .then((cache) => Promise.allSettled(PRECACHE.map((u) => cache.add(u))))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

/* Stale-while-revalidate: answer instantly from cache, then quietly refresh it
   so the next visit has the newest version. No deploy step has to remember to
   bump anything. */
self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;   // never touch third parties

  /* Pages are cached under the spelling the host serves (/for-teachers) but
     linked as for-teachers.html, because the .html links are what let the site
     open straight off a memory stick over file://. So either spelling can
     arrive here; a miss checks the other one before giving up on the cache. */
  const leaf = url.pathname.slice(url.pathname.lastIndexOf('/') + 1);
  const alt = url.pathname.endsWith('.html')
    ? url.pathname.slice(0, -5)
    : leaf && leaf.indexOf('.') === -1 ? url.pathname + '.html' : null;

  event.respondWith(
    caches.match(req)
      .then((hit) => hit || (alt ? caches.match(alt) : undefined))
      .then((hit) => {
        const fresh = fetch(req)
          .then((res) => {
            if (res && res.status === 200 && res.type === 'basic') {
              const copy = res.clone();
              caches.open(CACHE).then((c) => c.put(req, copy));
            }
            return res;
          })
          .catch(() => null);

        if (hit) return hit;
        return fresh.then((res) => {
          if (res) return res;
          // offline and never cached: hand back a friendly page, not a browser
          // error. respondWith(undefined) throws, so this must always resolve
          // to a real Response even if the fallback page is missing too.
          if (req.mode === 'navigate') {
            return caches.match('/404')
              .then((r) => r || caches.match('/404.html'))
              .then((r) => r || OFFLINE());
          }
          return new Response('', { status: 504, statusText: 'Offline' });
        });
      })
  );
});

function OFFLINE() {
  return new Response(
    '<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">' +
    '<title>Offline</title><body style="font-family:system-ui;text-align:center;padding:3em 1.5em;color:#2b2a5e">' +
    '<h1>No connection</h1><p>This page has not been saved for offline play yet.</p>' +
    '<p><a href="/games/" style="color:#2b2a5e">Back to the games</a></p>',
    { status: 503, headers: { 'Content-Type': 'text/html; charset=utf-8' } }
  );
}
