/* Play It My Way — offline service worker (generated by docs/build-pages.js)
 *
 * Caches the SITE'S OWN FILES so the games work with no connection. It stores
 * nothing about the child: no scores, no progress, no identifiers, no
 * analytics. There is deliberately no push code here — push would require a
 * per-device subscription held by a third party, which this site does not do.
 */
const CACHE = 'pimw-d20a4e06';

const PRECACHE = [
  "/",
  "/404.html",
  "/apple-touch-icon.png",
  "/components.css",
  "/components.js",
  "/disclaimer.html",
  "/favicon.svg",
  "/fonts/fredoka-400.woff2",
  "/fonts/fredoka-600.woff2",
  "/fonts/fredoka-700.woff2",
  "/for-teachers.html",
  "/games/",
  "/games/2048-slider/",
  "/games/balloon-pop/",
  "/games/catch-falling-object/",
  "/games/clock-shop/",
  "/games/code-the-robot/",
  "/games/color-matcher/",
  "/games/counting-game/",
  "/games/dot-to-dot/",
  "/games/drawing-pad/",
  "/games/first-strokes/",
  "/games/geography-explorer/",
  "/games/math-puzzle/",
  "/games/memory-game/",
  "/games/minesweeper/",
  "/games/one-line-draw/",
  "/games/rock-paper-scissors/",
  "/games/science-trivia/",
  "/games/sentence-builder/",
  "/games/silly-story-builder/",
  "/games/sort-it-out/",
  "/games/sound-it-out/",
  "/games/sudoku/",
  "/games/tic-tac-toe/",
  "/games/trace-letters/",
  "/games/trace-name/",
  "/games/trace-shapes/",
  "/games/whack-a-mole/",
  "/games/word-guess/",
  "/games/word-scramble/",
  "/icons/icon-192.png",
  "/icons/icon-512.png",
  "/icons/icon-maskable-512.png",
  "/privacy-policy.html",
  "/styles.css",
  "/tokens.css"
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE)
      // individually, so one bad URL cannot fail the whole install
      .then((cache) => Promise.allSettled(PRECACHE.map((u) => cache.add(u))))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

/* Stale-while-revalidate: answer instantly from cache, then quietly refresh it
   so the next visit has the newest version. No deploy step has to remember to
   bump anything. */
self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;   // never touch third parties

  event.respondWith(
    caches.match(req).then((hit) => {
      const fresh = fetch(req)
        .then((res) => {
          if (res && res.status === 200 && res.type === 'basic') {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(req, copy));
          }
          return res;
        })
        .catch(() => null);

      if (hit) return hit;
      return fresh.then((res) => {
        if (res) return res;
        // offline and never cached: hand back a friendly page, not a browser error
        if (req.mode === 'navigate') return caches.match('/404.html');
        return new Response('', { status: 504, statusText: 'Offline' });
      });
    })
  );
});
